<?php /** @var \App\Core\Block\Page $this */ ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="/shop/App/Core/view/theme/default/styles/styles.css">
  <script type="text/javascript" src="/shop/App/Core/js/jquery.js"></script>
    <title><?= $this->getTitle() ?></title>
</head>
    <body>
    <div class="header_logo">
      <a href="http://localhost/shop/"><img src="/shop/App/Core/view/theme/default/image/shop-icon.gif" alt="logo" width="100px"></a>

      <form action="http://localhost/shop/catalog/search/result" class="search-form">
        <input type="text" name="q">
        <input type="submit" value="Search" class="search-form__button">
      </form>
    </div>
      <div class="header_main">
          <ul class="header_main__menu">
            <li><a href="http://localhost/shop/"><b>HOME</b></a></li>
            <p><b>Categorys :</b></p>
              <?php echo $this->getCategoryList()->toHtml();?>
            <p><b>Edit :</b></p>
            <li><a href="/shop/catalog/product/add"><b>PRODUCT</b></a></li>
          </ul>
      </div>
      <div>
          <?php echo $this->getMainContentBlock()->toHtml(); ?>
      </div>
    </body>
</html>
