<?php /** @var $block \App\Catalog\Block\ProductView */?>
<?php /** @var $block \App\Catalog\Block\ProductList */?>

<div class="product-list">
    <?php foreach ($block->getProduct() as $products): ?>
      <a href="/shop/catalog/product/view/id/<?php echo $products->getId() ?>">
        <div class="product-list__info">
            <li>
                <img src="<?php echo ('/shop/uploaded/'.$products->getImage() ); ?>" alt="Product Image">
              <div class="text">
                   Name: <?php echo $products->getName()  ?><br>
                    Price : <?php echo $products->getPrice()?> $<br>
                    Category : <?php echo $products->getCategoryName() ?>
                <div class="product-info__add-to-cart-button">
                  <button>Add to Cart</button>
                </div>
              </div>

            </li>
        </div>
      </a>
    <?php endforeach; ?>
</div>
