<?php /** @var \App\Core\Block\Page $this */ ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="\shop\App\Admin\view\style\admin_login.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script type="text/javascript" src="\shop\App\Core\js\jquery.js"></script>
    <title><?= $this->getTitle() ?></title>
</head>
<body>
<p id="result_form"></p>
<div class="login">
  <h1>Login</h1>
  <form id="admin_login" action="\shop\admin\index\login" method="POST" enctype=multipart/form-data>
    <label for="username">
      <i class="fa fa-user"></i>
    </label>
    <input type="text" name="username" placeholder="Username" id="username" required>
    <label for="password">
      <i class="fa fa-lock"></i>
    </label>
    <input type="password" name="password" placeholder="Password" id="password" required>
    <input type="submit" value="Login">
  </form>
</html>
<script type="text/javascript" src="\shop\App\Admin\js\admin_login.js"></script>