<?php /** @var $block \App\Catalog\Block\ProductView */?>

<p id="delete" ></p>
<div class="product-info">
  <div class="product-info__edit">
    <a  id="product_delete" data-product-id="<?php echo $block->getProduct()->getId() ?>"><b>DELETE PRODUCT</b></a>
    <a href="/shop/catalog/product/edit/id/<?php echo $block->getProduct()->getId() ?>" ><b>EDIT PRODUCT</b></a>
  </div>
  <div class="product-info__category">
    <p><?php echo ($block->getProduct()->getCategoryName()); ?></p>
  </div>
  <div class="product-info__image">
    <img src="<?php echo ('/shop/uploaded/'.$block->getProduct()->getImage()); ?>" alt="Product Image">
  </div>

  <div class="product-info__total">
    <div class="product-info__name">
      <h3><?php echo ($block->getProduct()->getName()); ?></h3>
    </div>
    <div class="product-info__price">
      <p>PRICE : <?php echo ($block->getProduct()->getPrice()); ?> $</p>
    </div>
    <div class="product-info__sku">
      <p>sku : <?php echo ($block->getProduct()->getSku()); ?></p>
    </div>
    <div class="product-info__add-to-cart-button">
      <button>Add to Cart</button>
    </div>
  </div>
  <div class="product-info__description">
    <p><b>INFORMATION</b></p>
    <p><?= ($block->getProduct()->getDescription()) ?></p>
  </div>
</div>
<script type="text/javascript" src="\shop\App\Core\js\jquery.js"></script>
<script type="text/javascript" src="\shop\App\Admin\js\product_delete.js"></script>
